### ISSUE TITLE
hmda.rateSpread

### ISSUE THREAD

**Issue by dcantu476** [EncompassRest/EncompassRest#15]
Hi,

When attempting to open a loan using GetLoanAysnc the following Exception is thrown:

`Could not convert string to decimal: NA. Path 'hmda.rateSpread'`

It appears that the current schema in Encompass uses this field as a string, but if you pull the schema from the DeveloperConnect WebAPI it shows:
```
"RateSpread": {
          "nullable": false,
          "description": "Trans Details Rate Spread",
          "type": "NA<decimal>"
        }
```

Please let me know if you need anymore information.

**Comment by rbpeterson2** [comment]
I believe it is one of those weird legacy fields that have the field type
of “RA_STRING” that was mentioned in their last call that they would be
updated (field in Encompass: HMDA.X15)…



*Rob Peterson | *Managing Director*       Toll Free:* 855-374-TVMA ext.103
*Direct: *717-344-5554                          *Email:*
rpeterson@teraverde.com

[image: TV] <http://www.teraverde.com/needforspeed>

[image:
https://docs.google.com/uc?export=download&id=0B8aQtPTZx6czT09xc1JTVEN3VWc&revid=0B8aQtPTZx6czQnYwbm5UVUdBOUVVSWZkVWtNN2o1ekt5RXlrPQ]Follow
us on LinkedIn for the latest industry news and articles
<https://www.linkedin.com/company/1911368>

*Please don't print this e-mail unless you really need to. Be Green! *

***********************************************************************TVMA,
Inc. trades as Teraverde Management Advisors*

*Confidential Electronic Mail Notice:*
*The information contained in this message is intended only for the persons
to whom it is addressed and may contain privileged material. Copying,
distributing, dissemination, reliance on, or other use of the information
by persons other than the intended recipient(s) is prohibited. If you
received this message in error, please notify the sender and delete the
entire message from any computer.*



*From:* Damian Cantu [mailto:notifications@github.com]
*Sent:* Thursday, June 1, 2017 11:04 AM
*To:* hfcjweinstock/EncompassREST <EncompassREST@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* [hfcjweinstock/EncompassREST] hmda.rateSpread (#15)



Hi,

When attempting to open a loan using GetLoanAysnc the following Exception
is thrown:

Could not convert string to decimal: NA. Path 'hmda.rateSpread'

It appears that the current schema in Encompass uses this field as a
string, but if you pull the schema from the DeveloperConnect WebAPI it
shows:

"RateSpread": {

          "nullable": false,

          "description": "Trans Details Rate Spread",

          "type": "NA<decimal>"

        }

Please let me know if you need anymore information.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hfcjweinstock/EncompassREST/issues/15>, or mute the
thread

**Comment by TylerBrinkley** [comment]
I'm assuming you're using the AuthorizationRework branch? If so I just pushed a commit to support NA<decimal> types.

**Comment by TylerBrinkley** [comment]
Closing this as I believe this is resolved. If there are any other issues we can reopen it.
