### ISSUE TITLE
Proper way to "Disconnect"?

### ISSUE THREAD

**Issue by eidylon** [EncompassRest/EncompassRest#188]
Is there any way to instruct the API that it should consider us logged out now?

We have an API app using EncompassRest, and the client has it scheduled to run every 5 minutes. 
They are looking in some Encompass admin area and see a few hundred connections for the user account it runs under. They are concerned it will affect their Encompass fat-client performance.

So it looks like simply the act of the application terminating and the EncompassRestClient being cleaned up is not enough to close the Encompass connections. 

I'm guessing this is really something on Ellie Mae's side, that they are keeping the connections open excessively long, but just wanted to run it by the group here.

**Comment by TylerBrinkley** [comment]
I think if you call the `client.AccessToken.RevokeAsync` method it may clear up the connection on Ellie Mae's end, otherwise I'd think it would clean up after the token expires. I'd prefer to have that optionally done automatically when disposing of the client but unfortunately there is no `IAsyncDisposable` interface yet and I'd rather avoid a blocking call on `Dispose`.
