### ISSUE TITLE
TokenCreator.FromClientCredentialsAsync

### ISSUE THREAD

**Issue by xaph0n** [EncompassRest/EncompassRest#395]
I'm working a project as a partner for lenders to integrate with another company, and I noticed that there is a method on the TokenCreator for 'FromClientCredentialsAsync' that is marked as obsolete.  

I wanted to verify that this was just to bring attention to the fact that if the software isn't running as a partner integration solution, they should be using the from user credentials instead of from client credentials.  Additionally, I wanted to make sure that the 'FromClientCredentialsAsync' method wasn't slated to be removed.

Thanks,
Zach

**Comment by TylerBrinkley** [comment]
Yes, that is correct. That method and the similar one, [CreateFromClientCredentialsAsync](https://github.com/EncompassRest/EncompassRest/blob/950cc94b3ddebef57c0d60398d656a306c9d3491/src/EncompassRest/EncompassRestClient.cs#L230) on the `EncompassRestClient` are marked Obsolete so that most users aren't confused and accidentally use the wrong one when they want to use the user credentials flow since the client credentials flow is just for partner api users. Those methods aren't expected to be removed.

**Comment by xaph0n** [comment]
That is perfect, thank you.
