### ISSUE TITLE
Webhook serialize error

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#58]
Create Webhook no longer serializes correctly.

reason is "Unsupported Media Type"

**Comment by hfcjweinstock** [comment]
it has to do with the content length parameter.

**Comment by TylerBrinkley** [comment]
Is this a bug on our end or an Ellie Mae bug.

**Comment by hfcjweinstock** [comment]
not sure. working through it.  I believe it is on our end. I may be wrong about the location of the bug, but I need more time to go through it.

**Comment by ShaneHarrison** [comment]
@TylerBrinkley, I was able to subscribe using Postman. Haven't had a chance to dig into the details of the request in the EncompassRest Library yet.

**Comment by TylerBrinkley** [comment]
It appears this is due to 2 things, for one, the webhook endpoint doesn't seem to like the content-type including the charset=utf-8. This can be easily remedied. The second thing is that the webhook endpoint doesn't seem to like that the content-length is sometimes longer than the actual content length due to not knowing the json content length upfront in order to support serializing directly to a stream. It seems that since the other endpoints have no problem with this then Ellie Mae ought to update their end. As a temporary solution though we could have it serialize to a json string instead of a stream.

I'll submit a PR for this.
