### ISSUE TITLE
.net standard 1.1 vs 2.0

### ISSUE THREAD

**Issue by hfcjweinstock** [EncompassRest/EncompassRest#70]
I have looked at both, and i am wondering if we should support 2.0 instead of 1.1.  there are some features of 2.0 that might make things easier to manage.

**Comment by TylerBrinkley** [comment]
Library makers want to target the lowest possible .NET Standard version in order to be compatible with the most number of user applications. HttpClient is first exposed at .NET Standard 1.1 thus that's what I set it at. You can reference a .NET Standard 1.1 assembly from .NET Standard 2.0 however due to complications with massive number of assemblies included with using older .NET Standard versions in 2.0 we should also add a 2.0 build target.
