### ISSUE TITLE
Using EncompassRestClient.CreateFromAccessToken

### ISSUE THREAD

**Issue by amadard** [EncompassRest/EncompassRest#90]
I am trying to ensure my code remains as fast as possible, and my memory is that I should be able to continue to use my AccessToken for a while.  I am looking for some explanation of the EncompassRestClient.CreateFromAccessToken, to make sure I understand it correctly.

If I use CreateFromUserCredentialsAsync and pass in tokenExpirationHandling.RetrieveNewToken, and then retrieve the access token from that Client, and store it locally, will that automatically refresh the token if it is expired when I pass it into EncompassRestClient.CreateFromAccessToken ?

If my question is totally off base, what I am looking for is how to get an EncompassRestClient multiple times in the same application, across multiple threads, and have it return the EncompassRestClient as fast as possible over a large number of calls over a large amount of time.

Thanks!

**Comment by hfcjweinstock** [comment]
yes, your memory serves correctly.  you can reuse the same `EncompassRestClient` everywhere and not worry about the expiration if you pass the `RetrieveNewToken`.  be aware, this stores the username and password of the user account.

**Comment by TylerBrinkley** [comment]
The `EncompassRestClient` object should be thread-safe therefore you should be able to reuse just a single instance as long as it has the right permissions.

Passing the `TokenExpirationHandling.RetrieveNewToken` enum value to the `EncompassRestClient.CreateFromUserCredentialsAsync` method will store the username and password provided so that if a call to the API's results in a 401 Unauthorized error code, indicating an expired token, then the library will automatically retrieve a new token using the stored username and password and then resend the original request.

The `EncompassRestClient.CreateFromAccessToken` method was introduced to allow user's who already have an access token to be able to make calls to the Encompass API's with it. I personally have a use for it with an internal API I've created that accesses the Encompass API's which does authentication using the Encompass APIs. The Encompass API Token is embedded in our own Json Web Token so that the server is completely stateless.

**Comment by amadard** [comment]
Thanks Tyler, that is exactly what I was trying to remember!
